### ISSUE TITLE
Implement ExpandableSwipeListView Library

### ISSUE THREAD

**Issue by ghost** [reyalpsirc/ExpandableSwipeListView#1]
How to implement the demo project at this link https://github.com/47deg/android-swipelistview-sample#
with the help of above library. 

Thanks

**Comment by reyalpsirc** [comment]
Hi. First, sorry for the delay but I have not had to much time for this unfortunately.

Anyway, instead of implementing the sample on 47deg, I started implementing a really simple project as an example of this. It can take a little more time but, as soon as I have something I will push to the repo.
